version: "3"
services:
  web:
    image: nginx:alpine
    depends_on:
      - app
    ports:
      - ${NGINX_PORT}:80
    volumes:
      - ${PROJECT_PATH}:/work
      - ./logs:/var/log/nginx
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf

  app:
    build: ./docker/php
    ports:
      - ${LARAVEL_SERVER_PORT}:8000
    volumes:
      - ${PROJECT_PATH}:/work
      - ./docker/ash:/etc/profile.d
      - ./logs:/var/log/php
    working_dir: /work

  composer:
    build: ./docker/composer
    volumes:
      - ${PROJECT_PATH}:/work
    working_dir: /work

  db:
    build: ./docker/mysql
    volumes:
      - db:/var/lib/mysql
      - ./logs:/var/log/mysql
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - TZ=${TIMEZONE}
    ports:
      - ${MYSQL_PORT}:3306

  # db-testing:
  #   build: ./docker/mysql
  #   tmpfs:
  #     - /var/lib/mysql
  #     - /var/log/mysql
  #   environment:
  #     - MYSQL_DATABASE=${MYSQL_DATABASE}
  #     - MYSQL_USER=${MYSQL_USER}
  #     - MYSQL_PASSWORD=${MYSQL_PASSWORD}
  #     - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
  #     - TZ=${TIMEZONE}
  #   ports:
  #     - ${MYSQL_TESTING_PORT}:3306

  node:
    image: node:11-alpine
    volumes:
      - ${PROJECT_PATH}:/work
    working_dir: /work

  # redis:
  #   image: redis:alpine

  # mail:
  #   image: mailhog/mailhog
  #   ports:
  #     - ${MAILHOG_PORT}:8025

volumes:
  db:
    driver: local
